name: flutter_adaptive_scaffold_example
description: Multiple examples of the usage of the AdaptiveScaffold widget and its lower level widgets.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.1.0
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold:
    path: ..

dev_dependencies:
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/potato.png
    - images/habanero.png
    - images/strawberry.png
    - images/plum.png
    - images/mushroom.png
    - images/avocado.png
