name: image_picker_for_web_integration_tests
publish_to: none

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker_for_web:
    path: ../
  image_picker_platform_interface: ^2.8.0
  web: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
