name: file_selector_web_integration_tests
publish_to: none

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

dependencies:
  file_selector_platform_interface: ^2.6.0
  file_selector_web:
    path: ../
  flutter:
    sdk: flutter
  web: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
