name: google_maps_flutter_web_integration_tests
publish_to: none

# Tests require flutter beta or greater to run.
environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter_platform_interface: ^2.5.0
  google_maps_flutter_web:
    path: ../
  web: ^0.5.0

dev_dependencies:
  build_runner: ^2.1.1
  flutter_test:
    sdk: flutter
  google_maps: ^7.1.0
  google_maps_flutter: ^2.2.0 # Needed for projection_test.dart
  http: ">=0.13.0 <2.0.0"
  integration_test:
    sdk: flutter
  mockito: 5.4.4

dependency_overrides:
  # Override the google_maps_flutter dependency on google_maps_flutter_web.
  # TODO(ditman): Unwind the circular dependency. This will create problems
  # if we need to make a breaking change to google_maps_flutter_web.
  google_maps_flutter_web:
    path: ../
